import Head from "next/head";
import Footer from "../Footer/Footer";

export default function MainLayout({children}: any) {


  return (
    <div className={"App"}>
      <Head>
        <title>team.</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>
      <main>
        {children}
      </main>
      <Footer/>
    </div>
  );
}
